### PR TITLE
Bump go version to 1.15

### LINKED ISSUE #278: Go version is updated to v1.15
Currently, the project is using Go 1.12 which is [already end of life](https://endoflife.date/go).

AC:
- [ ] Update the project to use Go 1.15

### PR DESCRIPTION
**Pull request by BradleyBoutcher**
### What does this PR do?
Bump go version to 1.15

### What ticket does this PR close?
Resolves #278  

#### Change log
- [ ] The CHANGELOG has been updated, or
- [X] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [X] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [X] This PR does not require updating any documentation

### CODE REVIEW

**Comment by orenbm** [comment]
@BradleyBoutcher what's the motivation for this change?

**Comment by izgeri** [comment]
@orenbm we're standardizing all of our Go projects on the latest Go version 1.12 and 1.13 are already technically end of life.

**Comment by BradleyBoutcher** [comment]
@orenbm There's a ticket you filed, #278

**Comment by orenbm** [comment]
> @orenbm There's a ticket you filed, #278

I always trust Oren of the Past :)

Thanks!

**Review by orenbm — APPROVED** [review]

**Comment by izgeri** [comment]
@BradleyBoutcher I am just seeing that the Dockerfiles have go versions that are still stuck at 1.13 - can you please put up a follow-up PR to resolve this?

**Pull request merged**
