### PR TITLE
Bump version to 1.1.2

### LINKED ISSUE #287: There is a new release of the Secrets Provider that includes 4.5 support
There is a new release of the Secrets Provider that includes an announcement of the up-to-date supported OpenShift version, including 4.5.

Depends on #265

### PR DESCRIPTION
**Pull request by izgeri**
### What does this PR do?
Bumps version to 1.1.2

### What ticket does this PR close?
Resolves #287 

#### Change log
- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [x] This PR does not require updating any documentation

### CODE REVIEW

**Review by orenbm — APPROVED** [review]

**Comment by orenbm** [comment]
@izgeri did you scan the project for vulnerabilities?

**Comment by izgeri** [comment]
@orenbm I didn't, but none of the dependencies changed and all of the automated scans continue to pass. (I don't have access to the system you typically use, btw)

**Comment by orenbm** [comment]
> @orenbm I didn't, but none of the dependencies changed and all of the automated scans continue to pass. (I don't have access to the system you typically use, btw)

@sigalsax do we need to run a scan in this case?

**Comment by sigalsax** [comment]
@izgeri @orenbm what changed between the versions? Was this just the bug Liav fixed?
Question for @moticless but I think it would be good to scan so we can stay ontop of things just incase new vulnerabilities were found. I can perform the scan if @izgeri you doesn't have permissions

**Comment by izgeri** [comment]
@sigalsax please do - I'd like to release this ASAP

**Pull request merged**
