### PR TITLE
Bump version to 1.4.1

### PR DESCRIPTION
**Pull request by jtuttle**

### CODE REVIEW

**Comment by szh** [comment]
Do we still need to update `version.go` with the new release process?

**Comment by jtuttle** [comment]
@szh Yes we do, but for some reason `version.go` was already set to 1.4.1 which is why it doesn't appear in this PR.

**Comment by szh** [comment]
Doesn't look like it to me...
https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/secrets/version.go#L6

**Comment by jtuttle** [comment]
Weird, that file isn't mentioned at all in the `CONTRIBUTING.md` release instructions. I'll add it in this branch.

**Comment by jtuttle** [comment]
@szh Okay, all set.

**Pull request merged**
