### PR TITLE
Remove unused ByteSlicePrintf util

### PR DESCRIPTION
**Pull request by orenbm**
Connected to #108, #79

When we changed the K8s secret update method from `patch` to `update`
we stopped using the util we built for it but didn't remove the util
itself.

### CODE REVIEW

**Comment by eladkug** [comment]
@orenbm Please change TEST_ID_6_no_patch_permission_to_secret to TEST_ID_6_no_update_permission_to_secret as well

**Comment by orenbm** [comment]
> @orenbm Please change TEST_ID_6_no_patch_permission_to_secret to TEST_ID_6_no_update_permission_to_secret as well

nice catch, thanks

**Comment by sigalsax** [comment]
@orenbm interested to know when moving from `patch` -> `update` meant we needed to stop using this function to print byte arrays?

**Comment by eladkug** [comment]
You can add in your description that it closed this  [issue](https://github.com/cyberark/secrets-provider-for-k8s/issues/108)

**Comment by orenbm** [comment]
> @orenbm interested to know when moving from `patch` -> `update` meant we needed to stop using this function to print byte arrays?

@sigalsax you can see the change [here](https://github.com/cyberark/secrets-provider-for-k8s/pull/79/files?file-filters%5B%5D=.go&file-filters%5B%5D=.sh&file-filters%5B%5D=.yml#diff-3f727de64553945f6775fea6ddf50b3eL71).

**Pull request merged**
