### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by szh**

### CODE REVIEW

**Comment by tzheleznyak** [comment]
Hey @szh 
Maybe the bump from here https://github.com/cyberark/secrets-provider-for-k8s/pull/420/files?authenticity_token=amuoq0W%2FYdoEdI0X8v43Xej%2F1cl386KBl3Vi5HO929sVapzT1Yyp1IDoOKWWHtQHpmEGc5GgDyU%2BTUHTKTw6pQ%3D%3D&file-filters%5B%5D=.go&file-filters%5B%5D=.sum

Should be part of the PR
https://github.com/cyberark/secrets-provider-for-k8s

**Comment by szh** [comment]
> Hey @szh Maybe the bump from here https://github.com/cyberark/secrets-provider-for-k8s/pull/420/files?authenticity_token=amuoq0W%2FYdoEdI0X8v43Xej%2F1cl386KBl3Vi5HO929sVapzT1Yyp1IDoOKWWHtQHpmEGc5GgDyU%2BTUHTKTw6pQ%3D%3D&file-filters%5B%5D=.go&file-filters%5B%5D=.sum
> 
> Should be part of the PR https://github.com/cyberark/secrets-provider-for-k8s

I think small PRs is best. Let's do one at a time

**Review by andytinkham — COMMENTED** [review]
LGTM

**Review by andytinkham — APPROVED** [review]
LGTM for now - approving so we can see if it fixes downstream dependencies

**Pull request merged**
