### PR TITLE
Add empty 1.4.5 section to Changelog

### PR DESCRIPTION
**Pull request by john-odonnell**
### Desired Outcome

Keep the Changelog current for automated builds.

### Implemented Changes

N/A

### Connected Issue/Story

Resolves #[relevant GitHub issue(s), e.g. 76]

CyberArk internal issue link: [insert issue ID]()

### Definition of Done
*At least 1 todo must be completed in the sections below for the PR to be
merged.*

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

### CODE REVIEW

**Comment by szh** [comment]
Do we add a link href now or wait until actual release?

**Comment by john-odonnell** [comment]
@szh the link will be broken until the next release anyways 🤷

**Comment by szh** [comment]
True, but we don't do a new commit when we release so it'll end up not having a link. @ismarc What's the indented workflow regarding this?

**Review by jtuttle — APPROVED** [review]

**Comment by andytinkham** [comment]
Section added in #484.

**Comment by ismarc** [comment]
> True, but we don't do a new commit when we release so it'll end up not having a link. @ismarc What's the indented workflow regarding this?

In other projects, and what has worked well, is to add (and update for the unreleased section) the link now, which will be broken until a release is promoted and begin working once it is, but provide all the correct content.

**Pull request closed without merging**
